apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-pod
  template:
    metadata:
      name: api-pod
      labels:
        app: api-pod
    spec:
      containers:
        - name: api-container
          image: app:latest
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: my-secrets
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: 600Mi
              cpu: 1
            requests:
              memory: 300Mi
              cpu: 500m
      restartPolicy: Always